### ISSUE TITLE
resolve with constructor Parameter

### ISSUE THREAD

**Issue by FalkoHilbert** [ybainier/Hypodermic#13]
Hi,

is there a Way to call  resolve with constructor Parameters, like
container->resolve< IServiceA >(5,"Hello World!");

**Comment by ybainier** [comment]
This way of using `Container::resolve< T >()` supposes you know the implementation behind `IServiceA`. Instead, you could register the concrete `IServiceA` like this:
```
ContainerBuilder builder;
builder.registerType< ServiceA >
(
    [](IComponentContext&)
    {
        return std::make_shared< ServiceA >(5, "Hello World!");
    }
).as< IServiceA >();
```

**Comment by FalkoHilbert** [comment]
Thanks for the Answer, but i have to implementations of one interface with the same Consctructor Parameters and i want to build an Instace of the interface with the same dynamic parameters. So i can't "predefine" the constructor Parameter.
Could i give hte Container the Context so that this could make the Instace by the Context. 
to Explain an Examlpe in c# with StructureMap:

Registry (Config):
ObjectFactory.Initialize(
        x =>
        {
                switch (dbtype)
                {
                        case "MSSQL":
                                x.For<IDatabase>().Use<MSSQLTable>();
                                break;
                        case "MySQL":
                                x.For<IDatabase>().Use <MySQLTable>();
                                break;
                }
        }
);

Instance Creating:

var args = new ExplicitArguments();
args.SetArg("connectionString", "THECONNECTIONSTRING READ BY CONFIG-XML");
ObjectFactory.GetInstance<IDatabase>(args);

Did You unterstand my Problem/Wish?

**Comment by d-led** [comment]
you should most probably abstract your `case` statement behind a type. That's exactly the anti-pattern the IOC is trying to solve. The `dbtype` should be a type and a dependency of `ServiceA`

**Comment by FalkoHilbert** [comment]
Thanks!
That's right, but this doesn't solve my problem with the constructor. Or I've got a little misunderstood?

**Comment by d-led** [comment]
My point was that you should rewrite your constructor. No code is forever,unless you write it for a spacecraft without an uplink :-)

**Comment by d-led** [comment]
On the other hand what I think you want is to achieve is a reconfiguration of types at runtime. @ybainier how would you solve that elegantly?
