### ISSUE TITLE
Type dependencies

### ISSUE THREAD

**Issue by amitkanfer** [ybainier/Hypodermic#20]
Hello there,
Thanks for the very cool project.

Question 1:
I've been using the version you've published in the past, using the INJECT macro in order to declare dependencies of a type.

So for example:
builder.registerType< Car>(CREATE(new Car(INJECT(IDriver))))->as< ICar>()->singleInstance();

in this example, i need to be familiar only with the IDriver interface.

I see that you changed this implementation and now the above should look something like this:

builder.registerType< Car>().with< IDriver, Driver >().as< ICar>().singleInstance();

right?
But now it seems like i need to be familiar with both IDriver and **Driver**

Am i missing something?

Question 2:
Does the new version compiles faster comparing to the previous release?

Thanks alot,
Amit

**Comment by ybainier** [comment]
Hi Amit,

The new version of Hypodermic takes you by the hand. Basically, when you wrote

builder.registerType< Driver >().as< IDriver >();

builder.registerType< Car >(CREATE(new Car(INJECT(IDriver))))
       .as< ICar >()
       .singleInstance();

now you can write

builder.registerType< Driver >().as< IDriver >();
builder.registerType< Car >().as< ICar >().singleInstance();

because you no longer need to describe the look of the constructor of Car.

More specifically, you only have to register types when you need to configure them. That is, their lifetime, or when they have to be known as an interface, or they have a very specific constructor not accepting instance types that Hypodermic can inject.

As a last example, if IDriver didn’t exist, well, if Car was accepting a Driver, you could only describe Car

builder.registerType< Car >().as< ICar >().singleInstance();

and if Car didn’t need to be known as ICar or be a single instance, you could just resolve Car without registering anything (doing so is harmless of course).

If you have any further questions, feel free to get back to me.

Thanks for the cheerings, it is always appreciated.

Yohan

**Comment by amitkanfer** [comment]
Thanks Yohan,

I tried following your guidelines, and i'm getting this error:

ContainerBuilder.h:27:81:   required by substitution of 'template<class T> typename Hypodermic::RegistrationDescriptorBuilder::ForTypeConstruction<T>::Type& Hypodermic::ContainerBuilder::registerType() [with T = FG::S2CMessageDispatcher]'

static assertion failed: Could not autowire T: you should consider registering T either by providing an instance or an instance factory

This is the class:

class S2CMessageDispatcher : public IS2CMessageDispatcher {

as you can see - it's implementing IS2CMessageDispatcher .

Can you help me understand what's the issue?

Thanks,
Amit

**Comment by ybainier** [comment]
Can you show me the ctor of your class? (Is it public?)

**Comment by amitkanfer** [comment]
no it's not public... can i private send it to you somehow?

**Comment by amitkanfer** [comment]
It looks something like this:

        S2CMessageDispatcher(std::shared_ptr<IA>a_handler,
                             std::shared_ptr<IB> b_handler,
                             std::shared_ptr<IC> c_handler,
                             std::shared_ptr<ID> d_manager,
..... 
with ~40 dependencies like this, all interfaces.

**Comment by amitkanfer** [comment]
I assume the order in which i declare the the types doesn't matter, right?

**Comment by ybainier** [comment]
It doesn't.

**Comment by ybainier** [comment]
Well, this is it. Have a look at Config.h

Hypodermic is configured to inject up to 20 dependencies by default. You might be able to raise it to whatever the number you want.

**Comment by ybainier** [comment]
Public c++ wise. What you gave me is fine, I don't need to see the real names.

**Comment by amitkanfer** [comment]
That solved it, thanks.
One more thing..

i had a registration like this:
        builder.registerType< CommandlineParser >(
            [=](IComponentContext&) -> CommandlineParser*
            {
                return new CommandlineParser(argc, argv);
            }).as< ICommandlineParser >().singleInstance();

how should i implement it now?

**Comment by amitkanfer** [comment]
Is it equivelent to this:

`        builder.registerInstanceFactory([=](Container&)
        {
            return std::make_shared< CommandlineParser >(argc, argv);
        }).singleInstance();`

If i try this - i'm getting this compilation error:
`/home/amitkanfer/dev/unified_fireglass/vb/3rd_party/Hypodermic/ProvidedInstanceFactoryRegistrationDescriptor.h:65:50: error: within this context
             updatedDescriptor->m_instanceFactory = m_instanceFactory;
`

thanks alot :)

**Comment by ybainier** [comment]
That should do it

builder.registerInstanceFactory([](Container&)
{
    return std::make_shared< CommandlineParser >(argc, argv);
}).as< ICommandlineParser >().singleInstance();

**Comment by ybainier** [comment]
Yes, so I should investigate... What kind of unit test can I build to make this fails like your code?

**Comment by amitkanfer** [comment]
Just declare a class like this one:

class CommandlineParser : public ICommandlineParser
{
public:
        CommandlineParser(int argc, const char **argv);
}

and interface:
class ICommandlineParser
{
public:

        // This accepts an unordered_map and appends all configuration variables to it
        virtual bool ParseCommandLine() = 0;
}

register like this:
`        builder.registerInstanceFactory([=](Container&)
        {
            return std::make_shared< CommandlineParser >(argc, argv);
        }).as< ICommandlineParser >().singleInstance();`

compilation should fail.

**Comment by ybainier** [comment]
Can you run the test suites? Are they ok? There is one that kind of look like yours in ProvidedInstanceFactoryRegistrationTests.cpp

**Comment by ybainier** [comment]
Ok, you may pull in a couple of minutes.

**Comment by ybainier** [comment]
Thank you very much for pointing out this issue.

**Comment by ybainier** [comment]
You are all set. Thanks again

**Comment by amitkanfer** [comment]
Thanks alot!
