### ISSUE TITLE
No release/tags

### ISSUE THREAD

**Issue by bmgandre** [ybainier/Hypodermic#21]
There is no tags in this repository which makes hard to know what is considered stable or not.
@ybainier, can you include some tags/releases?

**Comment by ybainier** [comment]
Hi André, I added the two initial tags of this project. That is, the first one _v1.0_ aims to be the _previous version_ of the software; it's the previous design and it lacks a couple of features. The randomly named _v2.1_ is the _latest stable_ version. Actually, you could clone this repository today and have a working version.

**Comment by bmgandre** [comment]
Thanks @ybainier !
