### ISSUE TITLE
Resolution by name using TBase as T itself

### ISSUE THREAD

**Issue by Rogiel** [ybainier/Hypodermic#22]
The named binder requires that a `TBase` parameter is passed to it. However, this makes impossible to create a named reference to objects without a base class, due to its `EnforceBaseOf` implementation.

```````
struct MyClass {};
Hypodermic::ContainerBuilder builder;
builder.registerType<MyClass>.named<MyClass>(); // fails with TBase should be a base of T
```````

By changing `EnforceBaseOf` `static_assert` to 
```````
static_assert(std::is_base_of< TBase, T >::value, "TBase should be T itself or a base of T");
```````
the code compiles and run fine, but this does not seem like a clean solution to this problem.

Is there any specific reason why you have explicitly excluded non-polymorphic classes from the named resolution? If you think this solution is good enough, I can provide a pull request with the given changes and some test cases.

**Comment by ybainier** [comment]
Hi Rogiel,

I've overloaded the `named` method to allow what you need. You can find the related changes in that commit: 581333c2a86450ea25b3432358b54fa3503489d2.

Is this solution good for you?

**Comment by Rogiel** [comment]
Perfect! Thank you.
