### ISSUE TITLE
pkg-config: 'libdir' not defined

### ISSUE THREAD

**Issue by pck** [ybainier/Hypodermic#27]
Hello.

The generated pkgconfig/libhypodermic.pc doesn't work because `libdir` is not set.
I'm not sure, but maybe the "Libs: .. -lboost_system" line isn't even necessary and can be deleted.

> $ pkg-config --cflags libhypodermic
> Variable 'libdir' not defined in '/usr/local/lib/pkgconfig/libhypodermic.pc'

Kind regards, Paul

**Comment by ybainier** [comment]
Hi Paul, thanks for reporting this issue. To tell the truth, I was given this file and I did not check that it worked throughout the modifications made to hypodermic. Could your please try your modifications and create a pull request with something that works? I would appreciate.

**Comment by pck** [comment]
I created a pull-request: #29
