### ISSUE TITLE
Visual Studio 2017 does not build lib

### ISSUE THREAD

**Issue by skalinkin** [ybainier/Hypodermic#32]
I have clone the repository. open solution right click on the Hypodermic project and select build option.

1>------ Rebuild All started: Project: Hypodermic, Configuration: Debug x64 ------
========== Rebuild All: 1 succeeded, 0 failed, 0 skipped ==========

that is all what I got and there is no Hypodermic.lib in output folder.

Please help.

**Comment by ybainier** [comment]
Did you succeed in building your first app using Hypodermic?

**Comment by skalinkin** [comment]
Yes, now we trying to understand unique pointers usage.

You can look at our project here https://github.com/skalinkin/DevMorningFix

We also are trying to figure out the best way to include dependency. I am a
little bit spoiled by NuGet.
