### ISSUE TITLE
Support for C++17

### ISSUE THREAD

**Issue by Keeo** [ybainier/Hypodermic#33]
Any plans to support C++17? It currently fails on removed `std::unary_function` http://www.cplusplus.com/reference/functional/unary_function/

**Comment by judgeaxl** [comment]
You just need to change the hash function like this:

```
template <>
struct hash< Hypodermic::TypeInfo >
{
    using argument_type = Hypodermic::TypeInfo;
    using result_type = std::size_t;

    result_type operator()(const argument_type& value) const
    {
        return hash< type_index >()(type_index(value.intrinsicTypeInfo()));
    }
};
```

**Comment by ybainier** [comment]
Hi, I removed `std::unary_function` in the commit 373a50cfc9a01b77da59ec1d41418e3619b90ad8.

Thanks for letting me know about this issue which I will close right now ; feel free to reopen it if it is not solved on your side.
