### ISSUE TITLE
Current syntax for register factory with arguments

### ISSUE THREAD

**Issue by TalSolomon3** [ybainier/Hypodermic#37]
hi,
Currently i'm using a very old Hypodermic version with the following syntax:
        builder.registerType< FooFactory >(CREATE(std::make_shared< FooFactory >(	         
                 INJECT(IClass1),	
                 INJECT(IClass2)	
         ))).as< IFooFactory >().singleInstance();
where IClass1 and IClass2 are the params to FooFactory ctor.

I'm not sure how to convert it to the current syntax (without CREATE and INJECT). 
I tried builder.registerInstanceFactory and builder.registerInstance and it didn't work. 
I also tried to pass the params with context.resolve / container->resolve and it didn't work.

so what should i do?    thanks!

**Comment by ybainier** [comment]
Hi,

assuming you have something like

```
class Class1 : public IClass1
class Class2 : public IClass2

class FooFactory
{
    FooFactory(std::shared_ptr< IClass1 >, std::shared_ptr< IClass2 >);
};
```

you can write

```
ContainerBuilder builder;

// register and configure your abstract dependencies
builder.registerType< Class1 >()
       .as< IClass1 >();

builder.registerType< Class2 >()
       .as< IClass2 >();

// since v2 you no longer need to tell the container what FooFactory constructor looks like
builder.registerType< FooFactory >()
       .as< IFooFactory >()
       .singleInstance();

// build the container
auto container = builder.build();

// eventually resolve your components
auto fooFactory = container->resolve< IFooFactory >();
```

you're all set. Does it work for you?

**Comment by TalSolomon3** [comment]
Thanks for the fast response!

It doesn't work for me, because i think i described my situation much simpler than it is.
My FooFactory gets 33 params in his ctor. Most of them also get params in their ctor, and so on. 
all the 33 params have registerType, but in different files, under the same folders.

when i leave only "builder.registerType< FooFactory >().as< IFooFactory >().singleInstance();"
  in the file it used to be, i'm getting the following exception :  
  ״ /Hypodermic/RegistrationDescriptorBuilder.h:20:13: error: static assertion failed: Could not autowire T: you should consider registering T either by providing an instance or an instance factory
             static_assert(Traits::HasAutowireableConstructor< T >::value, "Could not autowire T: you should consider registering T either by providing an instance or an instance factory"); ״

when i'm adding " builder.registerType< Class8 >().as< IClass8 >().singleInstance() " to the file where FooFactory is being registered i'm getting the following exception : " error: ‘ Class8’ was not declared in this scope 
note: suggested alternative: ‘IClass8’
error: no matching function for call to ‘Hypodermic::ContainerBuilder::registerType<<expression error> >()’   "

what do you recommend ? thanks again!

**Comment by ybainier** [comment]
Have a look at [Config.h](https://github.com/ybainier/Hypodermic/blob/master/Hypodermic/Config.h). You will see that the default max value for your constructor argument count is set to 20. You can override this number by defining `HYPODERMIC_OVERRIDE_CONSTRUCTOR_ARGUMENT_COUNT` in your app.

It should do the trick.

Maybe you should consider splitting your object's responsibility; that might decrease its dependencies and ease the writing of unit tests.

**Comment by TalSolomon3** [comment]
Thanks! it did worked!

**Comment by ybainier** [comment]
That's good news!

Cheers
