### ISSUE TITLE
Pass parameters to register type

### ISSUE THREAD

**Issue by TalSolomon3** [ybainier/Hypodermic#38]
Hi,

I have function which gets 2 params (primitive types: string and char*), and need to do register type to a class where the ctor needs those 2 params.

I found other old issue (from 2015) which answers a very similar issue https://github.com/ybainier/Hypodermic/issues/13    but i'm getting exception for using it:
error: ‘IComponentContext’ has not been declared
             [=](IComponentContext&)
                   ^~~~~~~~~~~~~~~~~
When trying to change IComponentContext to ComponentContext i'm getting:
error: static assertion failed: Could not autowire T: you should consider registering T either by providing an instance or an instance factory

So what is the right syntax?
Thanks!

**Comment by ybainier** [comment]
Hey,

I think you are looking for [this](https://github.com/ybainier/Hypodermic/wiki/Registering-components#register-a-factory).

Right?
