### ISSUE TITLE
static assertion failed: TArg should be a complete type

### ISSUE THREAD

**Issue by popov-aa** [ybainier/Hypodermic#41]
Hello. I got this compile error, when I try to use forward declaration of dependencies of my classes:

```
Hypodermic/ArgumentResolver.h:30: static assertion failed: TArg should be a complete type
IPBPolymasterMassStorage/EquipmentWizardPage.cpp:69: required from here
```

EquipmentWizardPage.h:
```
#ifndef EQUIPMENTWIZARDPAGE_H
#define EQUIPMENTWIZARDPAGE_H

class DataManager;
namespace Hypodermic {
class Container;
}

#include <DeviceGate/DeviceGateDeviceInformationMessage.h>
#include <Escar/DataTypes/EscarDataTypes.h>
#include <QWizardPage>
#include <memory>

namespace Ui {
class EquipmentWizardPage;
}

class EquipmentWizardPage : public QWizardPage {

    Q_OBJECT

public:
    explicit EquipmentWizardPage(
        std::shared_ptr<DataManager> dataManager,
        std::shared_ptr<Hypodermic::Container> container,
        QWidget* parent = nullptr);
    virtual ~EquipmentWizardPage() override;
...
};
```
EquipmentWizardPage.cpp:
```
#include "EquipmentWizardPage.h"
#include "DataContainers/GeneralDataContainer.h"
#include "Dialogs/EquipmentGetDialog.h"
#include "Managers/DataManager.h"
#include "ui_EquipmentWizardPage.h"
#include <Hypodermic/Container.h>

void EquipmentWizardPage::on_pbEquipmentChange_clicked()
{
69: auto equipmentGetDialog = m_container->resolve<EquipmentGetDialog>();
    equipmentGetDialog->setParent(this);
    equipmentGetDialog->setFilterByUnits(true);
    equipmentGetDialog->setUnitsReadOnly(true);
    equipmentGetDialog->setCheckedUnits(m_units);
    equipmentGetDialog->setSerialRequired(true);
    if (equipmentGetDialog->exec() == QDialog::Accepted) {
        m_equipment = equipmentGetDialog->selectedEquipment();
        m_equipmentSerial = equipmentGetDialog->selectedEquipmentSerial();
        updateUi();
    }
}
```
EquipmentGetDialog.h:
```
#ifndef EQUIPMENTGETDIALOG_H
#define EQUIPMENTGETDIALOG_H

class DataManager;

#include "Models/CustomStringListModel.h"

#include <Escar/DataTypes/EscarDataTypes.h>
#include <QDialog>
#include <memory>

namespace Ui {
class EquipmentGetDialog;
}

class EquipmentGetDialog : public QDialog {

    Q_OBJECT

public:
    explicit EquipmentGetDialog(
        std::shared_ptr<DataManager> dataManager,
        QWidget* parent = nullptr);
    ~EquipmentGetDialog();
...
};
```

When I use include of headers of dependencies classes everywhere instead of forward declaration it works fine on linux. I got allocation memory error on windows in this case.

**Comment by popov-aa** [comment]
I have written simple example: https://github.com/popov-aa/HypodermicTest
What's wrong?

**Comment by ybainier** [comment]
Hey,

ContainerBuilder::registerType< T >() autowiring relies on type traits is_constructible< T, Args… > to deduce how to build T (https://en.cppreference.com/w/cpp/types/is_constructible <https://en.cppreference.com/w/cpp/types/is_constructible>) which requires T to be complete. That’s the bad news: when you let this software handle the inversion of control, you have to let it know about your components definition by the time you register them.

Feel free to get back to me if you need any further details.

Cheers,

Yohan

**Comment by popov-aa** [comment]
Look at my example, please. When types A, B, and C are registered, they are all full types. What change should I make to the project (example) for it to be compiled?

**Comment by popov-aa** [comment]
I have found workaround: using of interfaces for hiding of dependencies.

main.cpp
```
    containerBuilder.registerType<B>().as<IB>();
```

C.cpp
```
void C::doC()
{
    m_container->resolve<IB>()->doB();
}
```

**Comment by ybainier** [comment]
I don't reproduce the issue you're facing with https://github.com/popov-aa/HypodermicTest when I build it with visual studio (vc142), even when I don't use your workaround; that is, no `IB.h` included and no registration _as_ `IB`.

Is everything working now?
