### ISSUE TITLE
Bug: interface is resolved twice from nested container if they are added as both .as<interface>() and .asSelf()

### ISSUE THREAD

**Issue by lerppana** [ybainier/Hypodermic#46]
Hi! Thanks for creating this awesome library, it has saved me so much time and headaches!

I took a fast screenshot from debugger to show my problem:
<img width="1001" alt="image" src="https://user-images.githubusercontent.com/4603821/130350274-125b42f5-80d5-4ec3-9fd9-879b4fd054ac.png">

So what is happening here is that I have container and then I'm supposed to reload the plugins at runtime when they are rebuilt (I simplified the code in screenshot to show the issue). Somehow all the systems are resolved twice when I resolve them from application container. I was able to narrow this down in having my systems registered `as<core::system>()` and `.asSelf()`. If I remove `asSelf()` the system is resolved only once from nested container container.

I'm not sure if this is just my setup or wider issue. I´m running 
macOS with AppleClang 12.0.5
Boost 1.75 from vcpkg

**Comment by ybainier** [comment]
Hi! This looks like an old issue that should be fixed with this commit: https://github.com/ybainier/Hypodermic/commit/a08bc704932c2c135537a9a2da76b48501e376fc

Thanks!

**Comment by lerppana** [comment]
Works like a charm, thank you!
