### ISSUE TITLE
How to inject a factory for named instances?

### ISSUE THREAD

**Issue by xoltar** [ybainier/Hypodermic#49]
https://github.com/ybainier/Hypodermic/wiki/Expressing-dependencies#injecting-an-instance-factory gives an example of injecting a function that can be used as a factory. However, this seems to only work with anonymously-registered types. It seems there's no way to get a factory function that I could pass a name to, to get a named implementation back, is that right? I tried requesting a function that takes a `const &string`, but that didn't compile. How hard would it be to add that feature?

**Comment by ybainier** [comment]
Yes, you are right, only components registrations can be named. If you want to resolve a named factory, you can workaround this by creating the factory yourself and register it with a name.

Let's create an example from a doc sample:
```cpp
class PipeLoader
{
public:
   explicit PipeLoader(std::function< std::shared_ptr< IPipe >() > factory);
};
```

we can write a `PipeFactory`:
```cpp
class PipeFactory
{
public:
   explicit PipeFactory(std::shared_ptr< IPipe > pipe);

   std::shared_ptr< IPipe > invoke() { return m_pipe(); }
};
```

tweak `PipeLoader`:
```cpp
class PipeLoader
{
public:
   explicit PipeLoader(std::shared_ptr< PipeFactory > factory);
};
```

and for instance, register this like so:
```cpp
builder.registerType< PipeFactory >()
       .named("PipeFactoryWorkaround");

builder.registerType< PipeLoader >()
       .with< PipeFactory >([](ComponentContext& context)
        {
            return context.resolveNamed< PipeFactory >("PipeFactoryWorkaround");
        };
```

does this work for you?

**Comment by xoltar** [comment]
Hi @ybainier thanks so much. This is actually not what I'm looking for, if I understand it right. I'm not looking for a named factory, I'm looking for a factory that takes names. Just like I can have a constructor dependency for std::function<shared_ptr<thing>()> and the container will automatically create it for me, I'd like to be able to ask for std::function<shared_ptr<thing>(const std::string&)> and have the container automatically create it for me. I can work around it by doing this:
```
template<typename T>
class Factory {
  private:
    std::shared_ptr<Container> m_container;
  public:
    explicit Factory(std::shared_ptr<Container> container) : m_container(container) {}
    std::shared_ptr<T> invoke(const std::string &name) {
      return container->resolveNamed<T>(name);
    } 
};

class Client {
  private:
    std::shared_ptr<Factory<Thing>> m_factory;
  public:
    explicit Client(std::shared_ptr<Factory<Thing>> factory): m_factory(factory) {}
    void do_stuff() {
       auto thing1 = m_factory.invoke("thing1");
       auto thing2 = m_factory.invoke("thing2");
    }
}
```
This actually works fine - maybe you could add an example like this to the docs if you decide not to implement the automatic std::function<std::shared_ptr<T>(const std::string&))> thing.

Thanks for looking at this!

**Comment by ybainier** [comment]
Your solution looks fine but it is quite specific to your use case so I don't think that's necessary to add this shortcut behavior.
