### ISSUE TITLE
Is it possible to specify the dependency explicitly while resolving

### ISSUE THREAD

**Issue by mmaarouf-2** [ybainier/Hypodermic#50]
Hi 

I have the following classes:

```
class IDatabaseConnection;

class RepositoryA : public IRepositoryA {
  RepositoryA(std::shared_ptr<IDatabaseConnection>);
};

class RepositoryB : public IRepositoryB {
  RepositoryB(std::shared_ptr<IDatabaseConnection>);
};

```

In some cases, I want the same `IDatabaseConnection` to be shared when constructing `RepositoryA` and `RepositoryB`:

```
auto db = container->resolve<IDatabaseConnection>();
db->startTransaction();

auto repoA = container->resolve<IRepositoryA>(); // here I want to pass db explicitly to the constructor
auto repoB = container->resolve<IRepositoryB>(); // here I want to use db explicitly to the constructor

db->commit();
```

Note that in other cases, sharing the `db` instance is not necessary or desired (which is the default behaviour of Hypodermic)

Is it possible to achieve this behaviour? and if so, could you please provide an example?

Thanks

**Comment by ybainier** [comment]
I am not sure to understand what you want to achieve. Here, both `RepositoryA` and `RepositoryB` should share the same `IDatabaseConnection` instance, right? So I would configure the container like so:

```cpp
builder.registerType< DatabaseConnection >()
       .as< IDatabaseConnection >()
       // share this component with every other components that depend on IDatabaseConnection
       .singleInstance();

builder.registerType< RepositoryA >
       .as< IRepositoryA >();

builder.registerType< RepositoryB >
       .as< IRepositoryB >();
```

and if you want another component to use another `IDatabaseConnection` well you could use another interface as a marker or configure the container to tell it to use a specific component instead, for instance:

```cpp
builder.registerType< RepositoryC >
       .as< IRepositoryC >()
       // override IDatabaseConnection resolution in this context to provide your own instance
       .with< IDatabaseConnection, TransientDatabaseConnection >();
```

Let me know if this works for you.

**Comment by mmaarouf-2** [comment]
@ybainier thanks for the quick response.

> I am not sure to understand what you want to achieve. Here, both RepositoryA and RepositoryB should share the same IDatabaseConnection instance, right?

Not really, only when we have a transaction, we would want for those 2 repositories to share the database connection instance. For example:

```
// Here it is important for RepositoryA and RepositoryB to share the db connection since we have a transaction 
auto db = DbConnection();     // Fresh database connection

auto repoA = RepositoryA(db);
// repoA.doSomeQuery();
auto repoB = RepositoryB(db);
// repoB.doSomeQuery();

// Only now, we commit the transaction
db.commit();
```

In the above, `RepositoryA` and `RepositoryB` are not special, and we might have other combination of other repositories that perform some queries that are part of the same transaction.

In addition, it would be really undesirable to have a single database connection over the life time of the application that is used by a certain Repository.

------------------

I imagine what I want  could look like:

```
auto db = container->resolve<IDatabaseConnection>();
auto RepositoryA = container->resolve<IRepositoryA>().withParameter<IDatabaseConnection>(db);
```
Please let me know if it makes more sense now.

**Comment by ybainier** [comment]
To answer your first question, no, this library does not allow to configure dependencies on the fly, well not like this.

But you could write something like this to ensure both repositories are configured with the same connection at the time of a transaction:

```cpp
class TransactionScope
{
public:
    TransactionScope(std::shared_ptr< IDatabaseConnection > connection,
                     std::shared_ptr< IRepositoryA > repoA,
                     std::shared_ptr< IRepositoryB > repoB)
    {
        m_repoA->configureConnection(connection);
        m_repoB->configureConnection(connection);
    }

    void doSomeQuery()
    {
        m_repoA->doSomeQuery();
        m_repoB->doSomeQuery();
    }

    ~TransactionScope()
    {
        m_repoA->resetConnection();
        m_repoB->resetConnection();

        m_connection->commit();
    }
};
```

or even create them everytime you need them by configuring a nested container:
```cpp
class TransactionScope
{
public:
    TransactionScope(std::shared_ptr< IDatabaseConnection > connection,
                         std::shared_ptr< Hypodermic::Container > container)
    {
        Hypodermic::ContainerBuilder builder;

        // IDatabaseConnection resolution will now provide only this instance in this nested container
        builder.registerInstance(connection);

        builder.registerType< RepositoryA >
               .as< IRepositoryA >();

        builder.registerType< RepositoryB >
               .as< IRepositoryB >();

        auto nestedContainer = builder.buildNestedContainerFrom(*container);

        m_repoA = nestedContainer->resolve< IRepositoryA >();
        m_repoB = nestedContainer->resolve< IRepositoryB >();
    }
};
```

Again, without the whole picture I am just guessing by giving corner cases workarounds.

**Comment by mmaarouf-2** [comment]
@ybainier thanks a lot for your detailed response. I think creating a `TransactionScope` class as you suggested might do the trick.
